name: Configs tests

on: [pull_request, push]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_nextflow_config:
    runs-on: ubuntu-latest
    name: Check if nextflow config runs in repository root
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - run: nextflow config -show-profiles ${GITHUB_WORKSPACE}

  profile_test:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.profile }} profile
    strategy:
      matrix:
        profile:
          - "ibba"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest-everything"
      - name: Check ${{ matrix.profile }} profile
        env:
          SCRATCH: "~"
          NXF_GLOBAL_CONFIG: awsbatch.config
        run: nextflow run ${GITHUB_WORKSPACE}/configtest.nf -profile ${{ matrix.profile }}
